# Generated by Django 4.2.2 on 2023-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customername',
            field=models.CharField(max_length=100),
        ),
    ]
